### PR TITLE
Utilities to read geometry and readout IDs from configuration.

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
Functions are provided to read parameters as geometry and readout IDs using FHiCL types, with validation.
This should encourage authors not to implicitly assume one-cryostat or one-TPC geometries.
The implementation will be greatly simplified with the implementation of Redmine issue #23669.

Documented via Doxygen and unit tested as usual.

### CODE REVIEW

**Comment by gartung** [comment]
code-checks

**Comment by gartung** [comment]
code-checks

**Comment by gartung** [comment]
trigger build

**Comment by knoepfel** [comment]
@PetrilloAtWork, is there any code in LArSoft that will use these utilities?

**Comment by PetrilloAtWork** [comment]
Not yet, of course.
But SBND and ICARUS will most likely have shared code which will use them.

**Comment by knoepfel** [comment]
@PetrilloAtWork, sorry for the delay in responding.  Before LArSoft adopts these utilities, I would prefer to see them being used by an experiment first.  Once it becomes apparent that sharing the utilities will result in less overall code for both LArSoft and its experiments, then I will be supportive of adopting them.

**Comment by knoepfel** [comment]
@PetrilloAtWork, is there a reason you would prefer these utilities to be in LArSoft instead of SBN?

**Comment by PetrilloAtWork** [comment]
So far, apart from the fact they have nothing specific to SBN, my only answer is "because when I start using them for DUNE I won't have to ask to move the code around again".
(incidentally, there is o `sbncode` yet, and that may take a while)

**Comment by knoepfel** [comment]
Thanks for the explanation.  We'll schedule it for this week's release.  We'll look forward to your LCM presentation on what these facilities provide for the LArSoft community.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
approve

**Pull request merged**
